/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Copyright 2026 Peter Csaszar */

/**
 * @file app/config_wizard.c
 * @brief First-run interactive config wizard (FEAT-37).
 *
 * Shared by tg-cli, tg-cli-ro, and tg-tui via `<binary> login`.
 * Interactive path: prompts the user for api_id and api_hash on a TTY,
 * suppressing echo for the hash.
 * Batch path: validates the values from argv without any prompts.
 * On success writes ~/.config/tg-cli/config.ini atomically (tmp+rename+fsync)
 * and chmods it 0600.
 */

#include "app/config_wizard.h"

#include "fs_util.h"
#include "platform/path.h"
#include "platform/terminal.h"

#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#define API_HASH_LEN 32
#define MAX_RETRIES   3

/* ---- Validation helpers ---- */

/**
 * @brief Parse @p s as a positive 32-bit decimal integer.
 * @return The parsed value, or -1 on error.
 */
static int parse_api_id(const char *s) {
    if (!s || !*s) return -1;
    char *end = NULL;
    long v = strtol(s, &end, 10);
    if (!end || *end != '\0') return -1;
    if (v <= 0 || v > 0x7FFFFFFF) return -1;
    return (int)v;
}

/**
 * @brief Validate @p s as a 32-char lowercase hex string.
 * @return 0 if valid, -1 otherwise.
 */
static int validate_api_hash(const char *s) {
    if (!s) return -1;
    size_t n = strlen(s);
    if (n != API_HASH_LEN) return -1;
    for (size_t i = 0; i < n; i++) {
        unsigned char c = (unsigned char)s[i];
        if (!((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')))
            return -1;
    }
    return 0;
}

/* ---- Config file write ---- */

/**
 * @brief Determine the config directory path (without creating it).
 *
 * Result is written into @p buf (length @p cap).
 * @return 0 on success, -1 if the platform directory is unknown.
 */
static int get_config_dir(char *buf, size_t cap) {
    const char *base = platform_config_dir();
    if (!base) return -1;
    snprintf(buf, cap, "%s/tg-cli", base);
    return 0;
}

/**
 * @brief Check whether @p path is a non-empty regular file.
 * @return 1 if the file exists and has size > 0, 0 otherwise.
 */
static int file_nonempty(const char *path) {
    struct stat st;
    if (stat(path, &st) != 0) return 0;
    return (S_ISREG(st.st_mode) && st.st_size > 0) ? 1 : 0;
}

/**
 * @brief Atomically write api_id + api_hash to config.ini.
 *
 * Writes to a temp file, fsyncs, then renames over the destination.
 * Sets the final file to mode 0600.
 *
 * @return 0 on success, -1 on any I/O error.
 */
static int write_config(const char *dir, int api_id, const char *api_hash) {
    char path[1024];
    char tmp_path[1040];
    snprintf(path,     sizeof(path),     "%s/config.ini", dir);
    snprintf(tmp_path, sizeof(tmp_path), "%s/config.ini.tmp", dir);

    /* Create the directory if needed. */
    if (fs_mkdir_p(dir, 0700) != 0) {
        fprintf(stderr, "login: cannot create config dir %s: %s\n",
                dir, strerror(errno));
        return -1;
    }

    /* Write temp file. */
    int fd = open(tmp_path, O_WRONLY | O_CREAT | O_TRUNC, 0600);
    if (fd < 0) {
        fprintf(stderr, "login: cannot open %s: %s\n", tmp_path, strerror(errno));
        return -1;
    }

    FILE *fp = fdopen(fd, "w");
    if (!fp) {
        fprintf(stderr, "login: fdopen failed: %s\n", strerror(errno));
        close(fd);
        return -1;
    }

    fprintf(fp, "# tg-cli configuration\n");
    fprintf(fp, "# Generated by `login` wizard. Do NOT share this file.\n");
    fprintf(fp, "api_id=%d\n", api_id);
    fprintf(fp, "api_hash=%s\n", api_hash);

    if (fflush(fp) != 0) {
        fprintf(stderr, "login: fflush failed: %s\n", strerror(errno));
        fclose(fp);
        return -1;
    }
    if (fsync(fileno(fp)) != 0) {
        fprintf(stderr, "login: fsync failed: %s\n", strerror(errno));
        fclose(fp);
        return -1;
    }
    fclose(fp);

    /* Atomic rename over destination. */
    if (rename(tmp_path, path) != 0) {
        fprintf(stderr, "login: rename failed: %s\n", strerror(errno));
        return -1;
    }

    /* Ensure correct permissions even if the file existed before. */
    chmod(path, 0600);

    return 0;
}

/* ---- Interactive wizard ---- */

int config_wizard_run_interactive(void) {
    if (!isatty(STDIN_FILENO)) {
        fprintf(stderr,
                "login: stdin is not a TTY — use batch mode:\n"
                "  <binary> login --api-id N --api-hash HEX\n");
        return -1;
    }

    /* Determine and check config path upfront. */
    char cfg_dir[1024];
    if (get_config_dir(cfg_dir, sizeof(cfg_dir)) != 0) {
        fprintf(stderr, "login: cannot determine config directory\n");
        return -1;
    }
    char cfg_path[1040];
    snprintf(cfg_path, sizeof(cfg_path), "%s/config.ini", cfg_dir);

    if (file_nonempty(cfg_path)) {
        fprintf(stderr,
                "login: %s already exists and is non-empty.\n"
                "       Pass --force to overwrite, or edit it manually.\n",
                cfg_path);
        return -1;
    }

    printf(
        "\nWelcome to tg-cli!  This one-time setup records your Telegram API\n"
        "credentials into %s (mode 0600).\n"
        "\n"
        "You need an api_id and api_hash from https://my.telegram.org\n"
        "For a step-by-step guide see: docs/user/setup-my-telegram-org.md\n"
        "\n"
        "  1. Log in with your phone number and the code Telegram sends.\n"
        "  2. Go to 'API development tools'.\n"
        "  3. Fill out the 'Create new application' form:\n"
        "      - App title: anything, e.g. \"my tg-cli\"\n"
        "      - Short name: any 5+ char slug\n"
        "      - Platform: Desktop\n"
        "      - Description: optional\n"
        "  4. Copy the numeric 'App api_id' and the 32-char 'App api_hash'.\n"
        "  5. Paste them below.\n"
        "\n"
        "Press Ctrl-C to abort at any time.\n"
        "\n",
        cfg_path
    );

    /* Prompt for api_id with retries. */
    int api_id = -1;
    for (int attempt = 0; attempt < MAX_RETRIES; attempt++) {
        char buf[64];
        printf("Enter your api_id: ");
        fflush(stdout);
        if (!fgets(buf, sizeof(buf), stdin)) {
            fprintf(stderr, "\nlogin: aborted\n");
            return -1;
        }
        /* Strip trailing newline. */
        size_t n = strlen(buf);
        while (n > 0 && (buf[n-1] == '\n' || buf[n-1] == '\r')) buf[--n] = '\0';

        api_id = parse_api_id(buf);
        if (api_id > 0) break;

        fprintf(stderr,
                "  Error: api_id must be a positive integer (e.g. 12345).\n");
        if (attempt == MAX_RETRIES - 1) {
            fprintf(stderr, "login: too many invalid attempts\n");
            return -1;
        }
    }

    /* Prompt for api_hash with echo suppressed and retries. */
    char api_hash[API_HASH_LEN + 4]; /* +4 for NUL + possible \r\n */
    memset(api_hash, 0, sizeof(api_hash));
    int hash_ok = 0;
    for (int attempt = 0; attempt < MAX_RETRIES; attempt++) {
        int n = terminal_read_password("Enter your api_hash: ",
                                        api_hash, sizeof(api_hash));
        if (n < 0) {
            fprintf(stderr, "\nlogin: aborted\n");
            return -1;
        }
        /* terminal_read_password already NUL-terminates; strip any trailing
         * newline that some implementations might leave. */
        size_t slen = strlen(api_hash);
        while (slen > 0 && (api_hash[slen-1] == '\n' || api_hash[slen-1] == '\r'))
            api_hash[--slen] = '\0';

        if (validate_api_hash(api_hash) == 0) {
            hash_ok = 1;
            break;
        }
        fprintf(stderr,
                "  Error: api_hash must be exactly 32 lowercase hex "
                "characters ([0-9a-f]).\n");
        if (attempt == MAX_RETRIES - 1) {
            fprintf(stderr, "login: too many invalid attempts\n");
            return -1;
        }
    }
    if (!hash_ok) return -1;

    printf("Verifying... OK (format valid)\n");

    if (write_config(cfg_dir, api_id, api_hash) != 0) return -1;

    printf("Saved to %s (mode 0600).\n", cfg_path);
    printf("Next: run the binary and enter your phone number to complete login.\n\n");
    return 0;
}

/* ---- Batch wizard ---- */

int config_wizard_run_batch(const char *api_id_str, const char *api_hash_str,
                             int force) {
    if (!api_id_str || !api_hash_str) {
        fprintf(stderr,
                "login: --api-id and --api-hash are both required in batch mode\n");
        return -1;
    }

    int api_id = parse_api_id(api_id_str);
    if (api_id <= 0) {
        fprintf(stderr,
                "login: --api-id must be a positive integer, got: %s\n",
                api_id_str);
        return -1;
    }

    if (validate_api_hash(api_hash_str) != 0) {
        fprintf(stderr,
                "login: --api-hash must be exactly 32 lowercase hex chars "
                "([0-9a-f]), got: %s\n",
                api_hash_str);
        return -1;
    }

    char cfg_dir[1024];
    if (get_config_dir(cfg_dir, sizeof(cfg_dir)) != 0) {
        fprintf(stderr, "login: cannot determine config directory\n");
        return -1;
    }

    char cfg_path[1040];
    snprintf(cfg_path, sizeof(cfg_path), "%s/config.ini", cfg_dir);

    if (!force && file_nonempty(cfg_path)) {
        fprintf(stderr,
                "login: %s already exists and is non-empty.\n"
                "       Pass --force to overwrite.\n",
                cfg_path);
        return -1;
    }

    if (write_config(cfg_dir, api_id, api_hash_str) != 0) return -1;

    printf("Saved to %s (mode 0600).\n", cfg_path);
    return 0;
}
